// Generated by delombok at Sun Sep 22 21:37:45 CST 2019
package com.zts.xtp.trade.model.request;

import com.zts.xtp.common.enums.MarketType;

public class ETFBaseQueryRequest {
    /**
     * 交易市场
     */
    private MarketType marketType;
    /**
     * ETF买卖代码
     */
    private String ticker;

    public int getMarketType() {
        return marketType.ordinal();
    }

    public void setMarketType(int marketType) {
        this.marketType = MarketType.forType(marketType);
    }


    @SuppressWarnings("all")
    public static class ETFBaseQueryRequestBuilder {
        @SuppressWarnings("all")
        private MarketType marketType;
        @SuppressWarnings("all")
        private String ticker;

        @SuppressWarnings("all")
        ETFBaseQueryRequestBuilder() {
        }

        @SuppressWarnings("all")
        public ETFBaseQueryRequestBuilder marketType(final MarketType marketType) {
            this.marketType = marketType;
            return this;
        }

        @SuppressWarnings("all")
        public ETFBaseQueryRequestBuilder ticker(final String ticker) {
            this.ticker = ticker;
            return this;
        }

        @SuppressWarnings("all")
        public ETFBaseQueryRequest build() {
            return new ETFBaseQueryRequest(marketType, ticker);
        }

        @Override
        @SuppressWarnings("all")
        public String toString() {
            return "ETFBaseQueryRequest.ETFBaseQueryRequestBuilder(marketType=" + this.marketType + ", ticker=" + this.ticker + ")";
        }
    }

    @SuppressWarnings("all")
    public static ETFBaseQueryRequestBuilder builder() {
        return new ETFBaseQueryRequestBuilder();
    }

    /**
     * ETF买卖代码
     */
    @SuppressWarnings("all")
    public String getTicker() {
        return this.ticker;
    }

    /**
     * ETF买卖代码
     */
    @SuppressWarnings("all")
    public void setTicker(final String ticker) {
        this.ticker = ticker;
    }

    @Override
    @SuppressWarnings("all")
    public String toString() {
        return "ETFBaseQueryRequest(marketType=" + this.getMarketType() + ", ticker=" + this.getTicker() + ")";
    }

    @SuppressWarnings("all")
    public ETFBaseQueryRequest() {
    }

    @SuppressWarnings("all")
    public ETFBaseQueryRequest(final MarketType marketType, final String ticker) {
        this.marketType = marketType;
        this.ticker = ticker;
    }

    @Override
    @SuppressWarnings("all")
    public boolean equals(final Object o) {
        if (o == this) return true;
        if (!(o instanceof ETFBaseQueryRequest)) return false;
        final ETFBaseQueryRequest other = (ETFBaseQueryRequest) o;
        if (!other.canEqual((Object) this)) return false;
        if (this.getMarketType() != other.getMarketType()) return false;
        final Object this$ticker = this.getTicker();
        final Object other$ticker = other.getTicker();
        if (this$ticker == null ? other$ticker != null : !this$ticker.equals(other$ticker)) return false;
        return true;
    }

    @SuppressWarnings("all")
    protected boolean canEqual(final Object other) {
        return other instanceof ETFBaseQueryRequest;
    }

    @Override
    @SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + this.getMarketType();
        final Object $ticker = this.getTicker();
        result = result * PRIME + ($ticker == null ? 43 : $ticker.hashCode());
        return result;
    }
}
