// Generated by delombok at Sun Sep 22 21:37:45 CST 2019
package com.zts.xtp.common.model;

public class ErrorMessage {
	/**
	 * 错误代码
	 */
	private int errorId;
	/**
	 * 错误信息
	 */
	private String errorMsg;
	/**
	 * 请求代码，用于定位该返回值对应的请求
	 */
	private int requestId;

	public int getErrorId() {
		return errorId;
	}

	/**
	 * 错误代码
	 */
	@SuppressWarnings("all")
	public void setErrorId(final int errorId) {
		this.errorId = errorId;
	}

	/**
	 * 错误信息
	 */
	@SuppressWarnings("all")
	public void setErrorMsg(final String errorMsg) {
		this.errorMsg = errorMsg;
	}

	/**
	 * 请求代码，用于定位该返回值对应的请求
	 */
	@SuppressWarnings("all")
	public void setRequestId(final int requestId) {
		this.requestId = requestId;
	}

	@Override
	@SuppressWarnings("all")
	public boolean equals(final Object o) {
		if (o == this) return true;
		if (!(o instanceof ErrorMessage)) return false;
		final ErrorMessage other = (ErrorMessage) o;
		if (!other.canEqual((Object) this)) return false;
		if (this.getErrorId() != other.getErrorId()) return false;
		final Object this$errorMsg = this.getErrorMsg();
		final Object other$errorMsg = other.getErrorMsg();
		if (this$errorMsg == null ? other$errorMsg != null : !this$errorMsg.equals(other$errorMsg)) return false;
		if (this.getRequestId() != other.getRequestId()) return false;
		return true;
	}

	@SuppressWarnings("all")
	protected boolean canEqual(final Object other) {
		return other instanceof ErrorMessage;
	}

	@Override
	@SuppressWarnings("all")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		result = result * PRIME + this.getErrorId();
		final Object $errorMsg = this.getErrorMsg();
		result = result * PRIME + ($errorMsg == null ? 43 : $errorMsg.hashCode());
		result = result * PRIME + this.getRequestId();
		return result;
	}

	@Override
	@SuppressWarnings("all")
	public String toString() {
		return "ErrorMessage(errorId=" + this.getErrorId() + ", errorMsg=" + this.getErrorMsg() + ", requestId=" + this.getRequestId() + ")";
	}

	@SuppressWarnings("all")
	public ErrorMessage() {
	}

	@SuppressWarnings("all")
	public ErrorMessage(final int errorId, final String errorMsg, final int requestId) {
		this.errorId = errorId;
		this.errorMsg = errorMsg;
		this.requestId = requestId;
	}

	/**
	 * 错误信息
	 */
	@SuppressWarnings("all")
	public String getErrorMsg() {
		return this.errorMsg;
	}

	/**
	 * 请求代码，用于定位该返回值对应的请求
	 */
	@SuppressWarnings("all")
	public int getRequestId() {
		return this.requestId;
	}
}
