// Generated by delombok at Sun Sep 22 21:37:45 CST 2019
package com.zts.xtp.trade.model.response;

public class OrderCancelResponse {
    /**
     * 撤单XTPID
     */
    private String orderCancelXtpId;
    /**
     * 原始订单XTPID
     */
    private String orderXtpId;
    /**
     * 此消息响应函数对应的请求ID
     */
    private int requestId;
    /**
     * 此消息响应函数是否为request_id这条请求所对应的最后一个响应，当为最后一个的时候为true，如果为false，表示还有其他后续消息响应
     */
    private boolean lastResp;

    @Override
    public String toString() {
        return "OrderCancelResponse [ orderXtpId:" + orderXtpId + "  orderCancelXtpId:" + orderCancelXtpId + "  requestId:" + requestId + "  lastResp:" + lastResp + " ]";
    }


    @SuppressWarnings("all")
    public static class OrderCancelResponseBuilder {
        @SuppressWarnings("all")
        private String orderCancelXtpId;
        @SuppressWarnings("all")
        private String orderXtpId;
        @SuppressWarnings("all")
        private int requestId;
        @SuppressWarnings("all")
        private boolean lastResp;

        @SuppressWarnings("all")
        OrderCancelResponseBuilder() {
        }

        @SuppressWarnings("all")
        public OrderCancelResponseBuilder orderCancelXtpId(final String orderCancelXtpId) {
            this.orderCancelXtpId = orderCancelXtpId;
            return this;
        }

        @SuppressWarnings("all")
        public OrderCancelResponseBuilder orderXtpId(final String orderXtpId) {
            this.orderXtpId = orderXtpId;
            return this;
        }

        @SuppressWarnings("all")
        public OrderCancelResponseBuilder requestId(final int requestId) {
            this.requestId = requestId;
            return this;
        }

        @SuppressWarnings("all")
        public OrderCancelResponseBuilder lastResp(final boolean lastResp) {
            this.lastResp = lastResp;
            return this;
        }

        @SuppressWarnings("all")
        public OrderCancelResponse build() {
            return new OrderCancelResponse(orderCancelXtpId, orderXtpId, requestId, lastResp);
        }

        @Override
        @SuppressWarnings("all")
        public String toString() {
            return "OrderCancelResponse.OrderCancelResponseBuilder(orderCancelXtpId=" + this.orderCancelXtpId + ", orderXtpId=" + this.orderXtpId + ", requestId=" + this.requestId + ", lastResp=" + this.lastResp + ")";
        }
    }

    @SuppressWarnings("all")
    public static OrderCancelResponseBuilder builder() {
        return new OrderCancelResponseBuilder();
    }

    /**
     * 撤单XTPID
     */
    @SuppressWarnings("all")
    public String getOrderCancelXtpId() {
        return this.orderCancelXtpId;
    }

    /**
     * 原始订单XTPID
     */
    @SuppressWarnings("all")
    public String getOrderXtpId() {
        return this.orderXtpId;
    }

    /**
     * 此消息响应函数对应的请求ID
     */
    @SuppressWarnings("all")
    public int getRequestId() {
        return this.requestId;
    }

    /**
     * 此消息响应函数是否为request_id这条请求所对应的最后一个响应，当为最后一个的时候为true，如果为false，表示还有其他后续消息响应
     */
    @SuppressWarnings("all")
    public boolean isLastResp() {
        return this.lastResp;
    }

    /**
     * 撤单XTPID
     */
    @SuppressWarnings("all")
    public void setOrderCancelXtpId(final String orderCancelXtpId) {
        this.orderCancelXtpId = orderCancelXtpId;
    }

    /**
     * 原始订单XTPID
     */
    @SuppressWarnings("all")
    public void setOrderXtpId(final String orderXtpId) {
        this.orderXtpId = orderXtpId;
    }

    /**
     * 此消息响应函数对应的请求ID
     */
    @SuppressWarnings("all")
    public void setRequestId(final int requestId) {
        this.requestId = requestId;
    }

    /**
     * 此消息响应函数是否为request_id这条请求所对应的最后一个响应，当为最后一个的时候为true，如果为false，表示还有其他后续消息响应
     */
    @SuppressWarnings("all")
    public void setLastResp(final boolean lastResp) {
        this.lastResp = lastResp;
    }

    @SuppressWarnings("all")
    public OrderCancelResponse() {
    }

    @SuppressWarnings("all")
    public OrderCancelResponse(final String orderCancelXtpId, final String orderXtpId, final int requestId, final boolean lastResp) {
        this.orderCancelXtpId = orderCancelXtpId;
        this.orderXtpId = orderXtpId;
        this.requestId = requestId;
        this.lastResp = lastResp;
    }

    @Override
    @SuppressWarnings("all")
    public boolean equals(final Object o) {
        if (o == this) return true;
        if (!(o instanceof OrderCancelResponse)) return false;
        final OrderCancelResponse other = (OrderCancelResponse) o;
        if (!other.canEqual((Object) this)) return false;
        final Object this$orderCancelXtpId = this.getOrderCancelXtpId();
        final Object other$orderCancelXtpId = other.getOrderCancelXtpId();
        if (this$orderCancelXtpId == null ? other$orderCancelXtpId != null : !this$orderCancelXtpId.equals(other$orderCancelXtpId)) return false;
        final Object this$orderXtpId = this.getOrderXtpId();
        final Object other$orderXtpId = other.getOrderXtpId();
        if (this$orderXtpId == null ? other$orderXtpId != null : !this$orderXtpId.equals(other$orderXtpId)) return false;
        return true;
    }

    @SuppressWarnings("all")
    protected boolean canEqual(final Object other) {
        return other instanceof OrderCancelResponse;
    }

    @Override
    @SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final Object $orderCancelXtpId = this.getOrderCancelXtpId();
        result = result * PRIME + ($orderCancelXtpId == null ? 43 : $orderCancelXtpId.hashCode());
        final Object $orderXtpId = this.getOrderXtpId();
        result = result * PRIME + ($orderXtpId == null ? 43 : $orderXtpId.hashCode());
        return result;
    }
}
